### ISSUE TITLE
some accents moved one character to the right

### ISSUE THREAD

**Issue by svenper** [ctrlcctrlv/TT2020#2]
Congratulations on the amazing font and happy new year!

One minor quirk is some accented characters, [e.g.](https://en.m.wikipedia.org/wiki/Pinyin#Tones)

```text
āēīōūǖ
áéíóúǘ
ǎěǐǒǔǚ
àèìòùǜ
```

![1](https://user-images.githubusercontent.com/15199675/71697510-194a1180-2db0-11ea-9c6f-1448c859f88d.png)

**Comment by ctrlcctrlv** [comment]
Please use precombined characters for now. I haven't added the mark feature yet. I'll leave this open so should I do so I can inform you.

**Comment by svenper** [comment]
Just for clarity, these are indeed precombined characters, e.g. **ǎ** is `U+01CE` single code point.

```text
U+0101  ā  Latin Extended-A    LATIN SMALL LETTER A WITH MACRON
U+0113  ē  Latin Extended-A    LATIN SMALL LETTER E WITH MACRON
U+012B  ī  Latin Extended-A    LATIN SMALL LETTER I WITH MACRON
U+014D  ō  Latin Extended-A    LATIN SMALL LETTER O WITH MACRON
U+016B  ū  Latin Extended-A    LATIN SMALL LETTER U WITH MACRON
U+01D6  ǖ  Latin Extended-B    LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
U+00E1  á  Latin-1 Supplement  LATIN SMALL LETTER A WITH ACUTE
U+00E9  é  Latin-1 Supplement  LATIN SMALL LETTER E WITH ACUTE
U+00ED  í  Latin-1 Supplement  LATIN SMALL LETTER I WITH ACUTE
U+00F3  ó  Latin-1 Supplement  LATIN SMALL LETTER O WITH ACUTE
U+00FA  ú  Latin-1 Supplement  LATIN SMALL LETTER U WITH ACUTE
U+01D8  ǘ  Latin Extended-B    LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
U+01CE  ǎ  Latin Extended-B    LATIN SMALL LETTER A WITH CARON
U+011B  ě  Latin Extended-A    LATIN SMALL LETTER E WITH CARON
U+01D0  ǐ  Latin Extended-B    LATIN SMALL LETTER I WITH CARON
U+01D2  ǒ  Latin Extended-B    LATIN SMALL LETTER O WITH CARON
U+01D4  ǔ  Latin Extended-B    LATIN SMALL LETTER U WITH CARON
U+01DA  ǚ  Latin Extended-B    LATIN SMALL LETTER U WITH DIAERESIS AND CARON
U+00E0  à  Latin-1 Supplement  LATIN SMALL LETTER A WITH GRAVE
U+00E8  è  Latin-1 Supplement  LATIN SMALL LETTER E WITH GRAVE
U+00EC  ì  Latin-1 Supplement  LATIN SMALL LETTER I WITH GRAVE
U+00F2  ò  Latin-1 Supplement  LATIN SMALL LETTER O WITH GRAVE
U+00F9  ù  Latin-1 Supplement  LATIN SMALL LETTER U WITH GRAVE
U+01DC  ǜ  Latin Extended-B    LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
```

**Comment by ctrlcctrlv** [comment]
I guess, this is for Pinyin?

Here's Firefox's rendering, notice that most of the characters render in a different font :

![2020-01-03-100308_1397x834_scrot](https://user-images.githubusercontent.com/838783/71703543-1d0d8080-2e10-11ea-91d9-b6df057bc471.png)

The problem seems to be, where my font is missing some precombined accented characters, the program you are using is attempting to build them&mdash;poorly. This could be because my font contains anchors intended for the use of its automated build system and not third party programs.

So, I need to either:

* add these missing precombined Pinyin characters, and
* add a `ccmp` table

Or:

* add real `mark` and `mkmk` tables to aid third party programs in proper building.

**Comment by svenper** [comment]
Yes, my Firefox does like yours, it seems Chrome attempts to fill in the blanks automatically.

Many fonts center the accents around x-axis 0 and mess with marks, but for a monospace maybe you could get away without marks, by moving the combining accents on the other side of the x-axis, causing a horizontally centered overlap. Height stacking could still be an issue though (e.g. **ǖ**).

**Comment by ctrlcctrlv** [comment]
Is there a pressing need for this? Do you really plan to write a document in Pinyin? Although it's used for writing the most spoken language on the planet, I thought Pinyin to be obscure, as native speakers have rejected it for anything but typing. No?

**Comment by svenper** [comment]
It's definitely no rush, I have nothing riding on this.

Even if pinyin is basically never used for body text, in English it pops up here and there, especially if you need to write a Chinese name. Leaving out the tone is common, but it's roughly the same as referring to a John Smith as "Jehn Mith".

Maybe this is not the domain of a hyperrealistic typewriter font but it never hurts to ask. :smile:

**Comment by ctrlcctrlv** [comment]
Gotcha. Don't worry, I do plan to fix it, but was just wondering if you needed it now or if I can take my sweet time releasing the fix. :)

**Comment by ctrlcctrlv** [comment]
Superseded by #4, #5 and #6.
