### ISSUE TITLE
lighter font versions for web

### ISSUE THREAD

**Issue by syffs** [ctrlcctrlv/TT2020#20]
SVG files can be so small that I'm wondering what makes these font files so heavy (style E woff2 ~1.7M) ?

Would it be possible to build lighter versions of these font for the web like 100-200K max

**Comment by ctrlcctrlv** [comment]
@syffs Why can't you subset the font?

**Comment by syffs** [comment]
@ctrlcctrlv not sure how to that ? like subsetting to a more restricted charset than UTF-8 ?
Now, looking at glyphs, it does look like vector paths are quite unoptimized.

**Comment by ctrlcctrlv** [comment]
@syffs Correct. E.g. `harfbuzz` can subset for you. It's out of scope for me to explain in this repo how to subset I think, but solutions exist.

Yes the paths are not optimized, I was going for realism above optimization. If you want to smooth out my paths with a third party utility like MFEKpathops or FontForge that's up to you.
