### ISSUE TITLE
Add link to website to GitHub repository page

### ISSUE THREAD

**Issue by lauritzt** [ctrlcctrlv/TT2020#29]
~~There is currently no link to the website on the repository page.~~ – Well, never mind, there is in fact one in the README... Though it would probably make sense to add it to the About section too.

Links can be added by clicking the cog symbol next to the About section in the sidebar to the right of the repository's main page.

Links seem to be missing from other of your projects, as well.

Many thanks for your wonderful work, @ctrlcctrlv!

**Comment by ctrlcctrlv** [comment]
done
