### ISSUE TITLE
non-opentype environments clean glyph fallbacks

### ISSUE THREAD

**Issue by svenper** [ctrlcctrlv/TT2020#3]
![hmm](https://user-images.githubusercontent.com/15199675/71712019-67d0cd80-2dfb-11ea-81cd-bfb9c1ff4a7f.png)

The font looks hella cool in a terminal, however terminals (and probably a bunch of other programs) are usually not very good at OpenType which results in the very problem you tried to solve of repeating glyphs, which goes especially for `K`, `P` and  `x`. For these types of scenarios I think a good compromise would be to ensure the first default glyph variant is not visibly jagged like these.

**Comment by ctrlcctrlv** [comment]
Your point is well-taken, though will probably be very hard for me to implement in the general case (without just doing through it manually and choosing the 'default' glyph).

As a quick fix in the mean time though: **Try it in `kitty`**
![2020-01-03-154644_2075x513_scrot](https://user-images.githubusercontent.com/838783/71712420-1c8cde00-2e40-11ea-95c8-d9fed8bf1926.png)

I can't recommend this terminal emulator enough. @kovidgoyal really broke through boundaries when developing it. It's not only better than Alacritty, a similar OpenGL terminal, but is _way_ better than Konsole, etc.

I think it uses Pango for layout, which is the correct way to do it. Ligatures also supported.

**Comment by ctrlcctrlv** [comment]
(Oh, and it should go without saying, but this font is not even remotely optimized for programming, lol. Perhaps if people are interested in that I can get us part of the way there by implementing a `zero` feature plus perhaps a stylistic set. Does every monospace font need to be a programming font?)

![2020-01-03-155331_2720x1215_scrot](https://user-images.githubusercontent.com/838783/71712645-10ede700-2e41-11ea-960c-ba352ace9317.png)

**Comment by svenper** [comment]
As long as `O` is wider than `0` my eyes are still young enough to see the difference. I'm just waiting for some poor movie director to actually use the font, but in Word 2003, and be back on square 0 haha

**Comment by kovidgoyal** [comment]
Thanks for the kind words, and just FYI, kitty does not use pango, it actually renders using just harfbuzz and freetype/coretext

**Comment by svenper** [comment]
I tried kitty with `disable_ligatures always` (since I don't want `f_i` ligature) but this very setting also seemingly disables the contextual alternates. Am I missing something?

**Comment by ctrlcctrlv** [comment]
@svenper This is the problem: https://github.com/kovidgoyal/kitty/blob/master/kitty/fonts.c#L779

The implementation seemingly turns off all OpenType features and not just ligatures, which is wrong.

@kovidgoyal is here, so maybe if you ask him nicely he'll make it so you can pass an array of features you want to `hb_shape`, similar to how CSS does it. Apparently "`hb_feature_from_string()` now accepts CSS font-feature-settings format."

Actually, I might take a crack at contributing to Kitty, since I love it so much, if he is too busy to fix this.

**Comment by ctrlcctrlv** [comment]
Oh and by the way @svenper, I'm sorry to say I'm closing this. The other fonts in the genre have some of the 'default' glyphs roughed up. I'm afraid that people will think that *none* of the glyphs are roughed up if I do what you want. Unfortunately FontSpace doesn't have `calt` enabled on font previews, and I presume many other sites have that problem.

If people are going to ignorantly use a font, it may as well be mine.
